Fix build on Windows: make libaccel_config.h be useable there
Without the declarations in it, we get a lot of build errors because
the types aren't declared.

```
hardware_configuration_driver.h:56:39: warning: 'struct accfg_ctx' declared inside parameter list will not be visible outside of this definition or declaration
hw_configuration_driver.c:134:9: error: conflicting types for 'dsa_driver_new_context'; have 'int32_t(struct accfg_ctx **)' {aka 'int(struct accfg_ctx **)'}
hardware_configuration_driver.h:56:9: note: previous declaration of 'dsa_driver_new_context' with type 'int32_t(struct accfg_ctx **)' {aka 'int(struct accfg_ctx **)'}

hw_configuration_driver.c:188:21: error: return type is an incomplete type
```
etc.

Fixes #38.